//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingResult
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public int Mark { get; set; }
        public int UserId { get; set; }
        public string Chapter { get; set; }
    
        public virtual User User { get; set; }
    }
}
